#!/bin/bash


/F2MD/executeF2MD "$1" 1 "$2" "$3" "$4" 30
python3 /F2MD/machine-learning-server/MLDatasetCollection.py "$1" "$4"
python3 /F2MD/machine-learning-server/MLOfflineTrainer.py "$1" "$4" "1.0"
/F2MD/executeF2MD "$1" 0 "$2" "$3" "$4" 5