#!/bin/bash


/F2MD/executeF2MD -s "$1" -a "$2" -c "$3" -ad 30 -ml "$4" -sd 1
python3 /F2MD/machine-learning-server/MLDatasetCollection.py "$4" "$3"
python3 /F2MD/machine-learning-server/MLOfflineTrainer.py "$4" "$3" "1.0"
/F2MD/executeF2MD -s "$1" -a "$2" -c "$3" -ad 5 -ml "$4" -sd 0