#!/bin/bash

tmux new-session -s F2MD   -n etc -d "cd /etc; bash -i"
tmux new-window  -t F2MD:1 -n var2   "sleep 60; touch I_was_here.txt; bash -i"
tmux send-keys -t F2MD:1 "tmux kill-session -t F2MD" Enter
tmux attach -t F2MD:1
printf "$(date)"