#!/bin/bash

tmux new-session -s F2MD -n etc -d "cd /etc; bash -i"
tmux new-window  -t F2MD:1 -n var "cd /F2MD/; ./testExec_Server > server-log.txt; bash -i"
sleep 5
tmux set-window-option -g remain-on-exit off
tmux new-window  -t F2MD:2 -n var2 "cd /F2MD/; ./testExec_Client > client-log.txt; bash -i" 
if [[ "$1" = "ATTACH" ]]
then
    tmux attach -t F2MD:2
fi