#!/bin/bash

if [ -f "MLOfflineTrainer.py" ] && [ -f requirements.txt ] && [ -f "save/valueSave_SVM_together.listpkl" ] && [ -f "save/targetSave_SVM_together.listpkl" ];
  then
    echo "Installing necessary python libraries and executing training"
    pip install -r requirements.txt
    python3 MLOfflineTrainer.py
else
    echo "Some files are missing"
fi
