#!/bin/bash
clear

if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit 1
fi


echo "called: python3 MLServer.py 9997 ${1} ${2} ${3}"
python3 /F2MD/machine-learning-server/MLServer.py 9997 "${1}" "${2}" "${3}"
