#!/bin/bash
clear

if [ -z "$1" ]; then
  echo "No argument supplied"
  exit 1
fi

if [[ "${1}" == *"LSTM"* ]]; then
  echo "called: python3 MLServer.py 9997 ${1} ${2} ${3} ${4} ${5} ${6}"
  python3 -u /F2MD/machine-learning-server/MLServer.py 9997 "${1}" "${2}" "${3}" "${4}" "${5}" "${6}"
else
  echo "called: python3 MLServer.py 9997 ${1} ${2} ${3} ${4} ${5}"
  python3 -u /F2MD/machine-learning-server/MLServer.py 9997 "${1}" "${2}" "${3}" "${4}" "${5}"
fi
